// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDggDUFbXboOV3gT_Q2CbxBo6D0V-ZTlCk',
    appId: '1:1066179756198:web:3192e827009b6fdbe3b467',
    messagingSenderId: '1066179756198',
    projectId: 'live-score-flutter',
    authDomain: 'live-score-flutter.firebaseapp.com',
    databaseURL: 'https://live-score-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'live-score-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdyRHOEB845CYP1fwieIplhdSZ3ZDm9VE',
    appId: '1:1066179756198:android:b4db73e67c0a579ce3b467',
    messagingSenderId: '1066179756198',
    projectId: 'live-score-flutter',
    databaseURL: 'https://live-score-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'live-score-flutter.appspot.com',
  );
}
